//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class AiStateGotoPlayer : IAiState
{
    private AiController aiController;
	public void Init(AiController aiController)
	{
	    this.aiController = aiController;
	}
	
	public void Update()
	{
        aiController.MoveTowardsPlayer();

        if (aiController.InAggroRadius() == true)
        {
            aiController.State = new AiStateAttacking();
        }
	}
}

